spring:
  config.activate.on-profile: "product"
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/Workspace/spring/example/database/mart
    username: sa
    password:
    hikari:
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: mart
  data:
    redis:
      host: localhost
      port: 6379
    ml:
      # ml server
      domain: ${ML_DOMAIN}
    push:
      domain: https://exp.host/--/api/v2/push/send